---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mqtt-config-claim
  namespace: mqtt
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mqtt-data-claim
  namespace: mqtt
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
     
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mqtt-log-claim
  namespace: mqtt
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
