---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault
  namespace: vault
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`vault.gerh.co.uk`)
    priority: 10
    services:
    - kind: Service
      name: vault
      namespace: vault
      passHostHeader: true
      port: 8200
